---

- name: Stop, start, or recycle QueryTool API
  hosts: querytool_api:&windows
  gather_facts: true
  serial: "{{ deploy_parallelism | default('25%') }}"
  any_errors_fatal: true

  vars:
    iis_application_name: "{{ querytool_api_application_name }}"
    iis_application_pool_name: "{{ querytool_api_application_pool_name }}"
    iis_application_healthcheck_url: "{{ querytool_api_application_healthcheck_url }}"

  tasks:
    - name: Stop QueryTool API
      ansible.builtin.import_role:
        name: common/stop_start_app_iis
        tasks_from: stop_app_iis.yml
      when:
        - stop_querytool_api is defined

    - name: Start QueryTool API
      ansible.builtin.import_role:
        name: common/stop_start_app_iis
        tasks_from: start_app_iis.yml
      when:
        - start_querytool_api is defined

    - name: Recycle QueryTool API
      ansible.builtin.import_role:
        name: common/stop_start_app_iis
        tasks_from: recycle_app_iis.yml
      when:
        - recycle_querytool_api is defined
