---

- name: "Start apppool for {{ iis_application_name | mandatory }}"
  ansible.windows.win_shell: >
    C:\Windows\System32\inetsrv\appcmd
    start apppool
    /apppool.name:{{ iis_application_pool_name | mandatory }}
  become: true
  become_method: runas
  become_user: "{{ ansible_facts['user_id'] }}"
  register: start_apppool_result
  failed_when:
    - start_apppool_result.rc != 0
    - start_apppool_result.stdout is not ansible.builtin.regex('Application pool .* already started', ignorecase=True)

- name: Run readiness probe after starting app pool
  ansible.builtin.include_role:
    name: common/healthcheck_app_iis
